FROM centos
RUN dnf install epel-release -y
RUN dnf install https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm -y
RUN dnf update -y
RUN dnf install postgresql
